regle pb double minishell avec ctrl-c

diff --git a/correction b/correction
--- a/correction
+++ b/correction
@@ -1,16 +1,5 @@
-valgrind --leak-check=full --show-leak-kinds=all --suppressions=supp.supp --track-fds=yes -q ./minishell
+valgrind --leak-check=full --show-leak-kinds=all --suppressions=supp.supp --track-fds=yes --trace-children=yes -q ./minishell
 
-# crash sur espaces/
-
-# bash-5.1$ /bin/ls safsafsa
-# /bin/ls: cannot access 'safsafsa': No such file or directory
-# bash-5.1$ echo $?
-# 2
-
-Minishell> /bin/cat
-fsdfds
-fsdfds
-^C
 Minishell> Minishell>
 
 # echo lol | cat -e
@@ -49,7 +38,72 @@ Minishell> echo $?
 
 (tester avec ctrl+D aussi)
 
-Minishell> rev << eof
-> abc
-> def
-> xyz
+# Minishell> rev << eof
+# > abc
+# > def
+# > xyz
+
+
+PRIO 
+	unset PATH into une commande ls par ex fonctionne alors que path n'existe plus
+	votre copie de env n'est pas changee lors d'un unset
+
+
+
+CD :
+
+	cd.c | ligne 55 rajouter verif if access(line, F_OK | X_OK) != 0 -> not a directory
+	pour un cd Makefile par exemple 
+
+HEREDOC 
+ -> plusieurs heredoc dans differents pipe leaks
+
+	cat << EOF | cat << EOF2 le deuxieme prend tout le contenu du premier heredoc au lieu de choper juste la suite a partir de >EOF
+
+	cat << EOF | cat << EOF -> ferme les 2 en meme temps au lieu d'attendre un EOF pour chacun
+
+
+ECHO 
+	echo -nnnnnnnnnn blablabla (pas obligatoire mais normalement ca considere comme -n)
+
+	echo $HOME = ${HOME}, gerer les ${VAR} 
+
+EXPORT 
+	export sdgsdg#d=gh devrait renvoyer message d'erreur + return value, check pour tous les autres characteres speciaux non autorises
+
+
+UNSET ne fait rien
+
+EXIT
+	exit s
+
+	- expected :
+		bash: exit: s: numeric argument required
+		➜  minishell git:(main) ✗ echo $?
+		2
+
+	au lieu de exit avrc return value 0
+
+	A comparer et implementer si besoin :
+		
+		exit s
+		exit s 213
+		exit 213 s
+
+
+REDIR 
+
+	IN :
+		cat < sdjkghds (existe pas/permission denied ...) faut exit l'exec du cat
+
+		!(surement resolu en meme temps que precedent)!
+		> echo "sdfsdfs" > file (no permission) should print Persmission denied with return value of 1 isntead of printing sdfsdfs on terminal
+		- add protection des open (partout) + print message d'erreur
+
+
+QUOTE
+	commande avec quote (bonne ou pas)
+	puis commande (non builtin) qui ne fonctionne pas ou builtin tout court avec pipe fait masse de leaks a cause de remove quotes qui n'a pas tout free 
+
+SIGNAL
+	SIGKILL (CTRL-\) dans l'execution d'une commande cat ou sleep devrait stopper l'execution
